### ISSUE TITLE
Feature. Loading passwords file looks like freeze.

### ISSUE THREAD

**Issue by curious-odd-man** [lyubick/passha#32]
When you enter master password it takes long time to load database - it looks like freeze.

It would be really great to see progress bar showing the progress of loading and keep UI responsive same time (be able to move window).

P.S. I can implement it, but I can't compile and run project because javafx is missing and should be added as dependency.

**Comment by lyubick** [comment]
Please feel free to do everything you see is required.

**Comment by lyubick** [comment]
Any estimations, just to plan if we required to go-live fix-by-fix or in bulk?

**Comment by curious-odd-man** [comment]
Implemented. Please review changes.
